### ISSUE TITLE
readthedocs build failure: missing ROOT dependency.

### ISSUE THREAD

**Issue by AndreasAlbert** [clelange/hepdata_lib#23]
For autodoc to work, we somehow need to make ROOT work on the readthedocs build machine.
The trouble is that AFAIK there is no way of executing a custom shell script before the build, so we cannot copy&paste the solution we use for travis.

One hacky solution would be to somehow cram the ROOT installation (e.g. via binary download as done with travis) into setup.py. In that case, we would have to make sure that this really only happens when installing the library on the build server and not for users.

**Comment by AndreasAlbert** [comment]
Some notes on what I have tried:

* Download root binaries and untar in python -> works trivially

* Sourcing thisroot.sh -> does not work. You can use `os.environ` to overwrite what python thinks most of the paths in environment variables are and thus propagate the effect of the source command into python. Unfortunately, this does not work for `LD_LIBRARY_PATH` as that is apparently cached at python startup, so changing it during runtime does not help. If this path is not set right, `import ROOT` fails because it cannot find various compiled libraries `lib*.so`. [StackOverflow](https://stackoverflow.com/questions/6543847/setting-ld-library-path-from-inside-python/25457751#25457751) turned up two workarounds, both of which do not work:
   * `os.execv` gives a permission denied error (probably because we do not have rights to start processes on the build machine?)
   * Using `cdll.LoadLibrary` to load a given library works, but it is not clear to me how to proceed for the >100 library files in `root/lib`. I tried just loading all of them, but that fails. Do you need to import them in the right order?

**Comment by AndreasAlbert** [comment]
[Maybe this works?](http://blog.rtwilson.com/how-to-make-your-sphinx-documentation-compile-with-readthedocs-when-youre-using-numpy-and-scipy/)

**Comment by clelange** [comment]
Yes, I think you need to use `mock`.

**Comment by clelange** [comment]
Can you assign the issue if you're working on it? Otherwise I might give it a go later when I'm tired of preparing presentation slides ;-)

**Comment by AndreasAlbert** [comment]
With mock, [building]( https://readthedocs.org/projects/hepdata-lib/builds/7196897/
) runs through now. There are plenty of sphinx/latex warnings, though and the build [does not produce the output](http://hepdata-lib.readthedocs.io/en/docu/source/hepdata_lib.html#module-contents). Not quite there yet.

**Comment by AndreasAlbert** [comment]
I think I was looking in the wrong documentation version before. Everything seems fine now.
