### ISSUE TITLE
Problem with Getting_started.ipynb

### ISSUE THREAD

**Issue by rappoccio** [clelange/hepdata_lib#51]
Seeing an issue when using ROOT 6.12.04 on Mac OS with python 2.7.14.

/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/yaml/representer.pyc in represent_data(self, data)
     55             data_types = self.get_classobj_bases(data.__class__)+list(data_types)
     56         if data_types[0] in self.yaml_representers:
---> 57             node = self.yaml_representers[data_types[0]](self, data)
     58         else:
     59             for data_type in data_types:

TypeError: unbound method represent_dict() must be called with Representer instance as first argument (got Dumper instance instead)

**Comment by AndreasAlbert** [comment]
Hi @rappoccio,

thanks for the report.
Could you check which PyYAML version you are using?
(Run `pip show PyYAML` in a terminal and copy the output).

Thanks

**Comment by rappoccio** [comment]
It's 4.1

```
Name: PyYAML
Version: 4.1
Summary: YAML parser and emitter for Python
Home-page: https://github.com/yaml/pyyaml
Author: Kirill Simonov
Author-email: xi@resolvent.net
License: MIT
Location: /opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages
Requires: 
Required-by: hepdata-lib

```

**Comment by AndreasAlbert** [comment]
Ok, that is the problem. I can reproduce your problem if I install `4.1`. I was previously running with `3.12`, which worked fine. So if you want to have a quick workaround, you can try downgrading to `3.12`.

As a way forward, I would propose to figure out what the right syntax for what we want to do is in 4.1, use that syntax,  and  update the setup requirements to make sure that at least this version is installed.

**Comment by rappoccio** [comment]
Aha, thanks for the quick checks! I can dig into this at some point soon if you don't get around to it.

**Comment by AndreasAlbert** [comment]
@rappoccio If you want to take a look, that would be very welcome! The technical issue here is that we want the `yaml` package to be able to dump our `default_dict` just as it would usually be able to dump a normal python `dict`. I expect this to be reasonably straightforward to fix. Please assign the issue to yourself once you start working on it to keep track of what's going on. Otherwise @clelange or I will look into it.

**Comment by rappoccio** [comment]
When I get around to it I will put the assignment in.

**Comment by clelange** [comment]
For which command in the notebook does this error show? I think we can fix it by using either `@staticmethod` or `@classmethod` as discussed at https://stackoverflow.com/questions/40701142/typeerror-unbound-method-must-be-called-with-instance-as-first-argument-got-in/40701173
I'll look into it.

**Comment by AndreasAlbert** [comment]
It happens any time we use `yaml.dump` to dump our `defaultdict`s.

**Comment by AndreasAlbert** [comment]
If we end up switching pyyaml versions, we should revisit #18

**Comment by clelange** [comment]
Hmm, so the offender seems to be https://github.com/clelange/hepdata_lib/blob/master/hepdata_lib/__init__.py#L18

I've created a new branch (https://github.com/clelange/hepdata_lib/tree/test_yaml_dump) with a couple of additional tests and forcing PyYAML to version 4.1, but I cannot reproduce the error. Can one of you take it from here?

**Comment by rappoccio** [comment]
I still see the error here. Running out of battery though so can't debug right now haha.

**Comment by AndreasAlbert** [comment]
Should be fixed in master now. @rappoccio please report if you encounter any more issues.

**Comment by rappoccio** [comment]
Thanks!

**Comment by clelange** [comment]
New version 0.2.2 is available on PyPI: https://pypi.org/project/hepdata_lib/
